version: '3.8'

services:

  db:

    image: postgres:15

    container_name: 'vk_db'

    env_file:
      - .env 

    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    
    volumes:
      - .postgres:/var/lib/postgres/data

    restart: always



  app:
    container_name: 'vk_api'

    build:
      context: .

    depends_on:
      - db

    env_file:
      - .env

    command: bash -c "alembic upgrade head; uvicorn api.main:app --host 0.0.0.0 --port 8000"

    ports:
      - 9999:8000